Add Terraform reference
aiven/devportal pull request #10
Opened 2021-05-17 12:53 UTC by jonatasbaldin

Hey there 👋 

This PR adds a Terraform reference, with a quick starting guide and pointing to the official docs ✨ 

TODO:
- [ ] Add UTM to the signup page link

2021-05-21 14:59 UTC, lornajane requested changes
Let's flesh out what's actually happening a bit, but this is a really good guide once it has a few more words

2021-05-21 14:59 UTC, lornajane commented on docs/tools/terraform.rst
> +Getting Started
Getting started with what? Let's add a little sentence about what we're getting you started with or to do.

2021-05-21 14:59 UTC, lornajane commented on docs/tools/terraform.rst
> +If you have any issues or would like to contribute to the tool, please join us on the `GitHub repository <https://github.com/aiven/terraform-provider-aiven>`_.
:+1: happy to see this included

2021-05-25 13:43 UTC, jonatasbaldin commented on docs/tools/terraform.rst
> +.. code:: bash
In the api_token line. There are best practices to separate code and configuration, but this is the most basic to get up and running.

2021-05-25 13:52 UTC, jonatasbaldin commented
hey, thanks for the review as always ✨ 

added some text around the issues you've commented while trying to keep it as succinct as possible

2021-06-01 13:40 UTC, lornajane approved these changes
This is a good addition! Minor changes added, and I'll wait for the build to build before merging.

2021-06-01 13:51 UTC, merged