MySQL: disable foreign key checks
aiven/devportal pull request #1190
Opened 2022-07-28 12:28 UTC by laysauchoa

Article migration:
https://help.aiven.io/en/articles/5580571-can-i-disable-foreign-key-checks

Fixes:

2022-07-29 08:13 UTC, ftisiot requested changes
Good one Laysa!
The command works for me!

I left some comments to make this article more "devportal" style, also please check the second `mysql` command is not shown in the preview

2022-07-29 08:13 UTC, ftisiot commented on docs/products/mysql/howto/disable-foreign-key-checks.rst
> +.. code::shell
Not sure why but this code is not shown in the preview

2022-07-29 08:13 UTC, ftisiot commented on docs/products/mysql/howto/disable-foreign-key-checks.rst
> +    mysql> SHOW VARIABLES LIKE 'foreign_key_checks';
Can we only show the actual code people need to copy/paste?
```suggestion
    SHOW VARIABLES LIKE 'foreign_key_checks';
```

2022-07-29 10:55 UTC, laysauchoa commented on docs/products/mysql/howto/disable-foreign-key-checks.rst
> +  * - ``USER_HOST``
I can replace to HOST if it helps

2022-07-29 11:01 UTC, laysauchoa commented on docs/products/mysql/howto/disable-foreign-key-checks.rst
> +It can be useful to know how to disable foreign key checks. For example, your migration to Aiven for MySQL may face foreign key violations which can result in an error, similar to::
Changed slightly, but seems good!

2022-07-29 11:05 UTC, laysauchoa commented
@ftisiot thanks for the review! addressed the comments. The last command did not work for me as I said on the PR description. So I was not sure if it was correct.

2022-08-01 07:12 UTC, ftisiot commented
@laysauchoa is this ready for review?

2022-08-01 07:18 UTC, laysauchoa commented
> @laysauchoa is this ready for review?

yes, I have added the last command in the last review, would be possible to check again? thank you

2022-08-01 07:23 UTC, ftisiot approved these changes
LGTM

2022-08-01 07:30 UTC, merged