Migration: Password Policy
aiven/devportal pull request #1256
Opened 2022-08-17 01:06 UTC by sluhur

This is related to this issue 1062 https://github.com/aiven/devportal/issues/1062

# What changed, and why it matters

2022-08-17 06:47 UTC, ftisiot requested changes
Hi @sluhur!
Thanks for this! I have a question: is this an howto or more a reference/concept one?

I left some comments that needs to be addressed.

Also it would be cool to have a dedicated howto on how to reset the password. I believe it would be one of the most clicked articles :D

2022-08-17 06:47 UTC, ftisiot commented on docs/platform/howto/password-policy.rst
> +Password Policy
as per warning this should be in sentence case :)

2022-08-17 06:47 UTC, ftisiot commented on docs/platform/howto/password-policy.rst
> +-  Cannot contain single repeating characters such as aaaaaaaa
I believe we can put `aaaaaaaa` as code to avoid the warning

2022-08-17 06:47 UTC, ftisiot commented on docs/platform/howto/password-policy.rst
> +-  Cannot contain common words, phrases or strings such as password, security, John . Using common words or service names can be easily guessed.
again if `John` it's the example, I would put it as code

2022-08-17 06:47 UTC, ftisiot commented on docs/platform/howto/password-policy.rst
> +-  Cannot contain words that are very similar to common words such as password1.
same comment, `password1`

2022-08-17 06:47 UTC, ftisiot commented on docs/platform/howto/password-policy.rst
> +**Password Tips**
Should this be a subtitle rather than highlighted in bold?

2022-08-17 06:47 UTC, ftisiot commented on docs/platform/howto/password-policy.rst
> +Selecting a strong password is a first step in securing your account. In addition to creating a secure password, please refer :doc:`./user-2fa`.
Maybe it's worth saying what you're referring to like "To know more about how you can strengthen your security by adding a two factor authentication read the dedicated documentation"

2022-08-17 06:47 UTC, ftisiot commented on docs/platform/howto/password-policy.rst
> +If you forget your password, you may reset your password by selecting ``Forgot Password``  on the `Aiven web console login <https://console.aiven.io/>`_ page.
```suggestion
If you forget your password, you may reset your password by selecting **Forgot Password**  on the `Aiven Console login <https://console.aiven.io/>`_ page.
```

2022-08-17 06:47 UTC, ftisiot commented on docs/platform/howto/password-policy.rst
> +If you have any questions, please feel free to contact the support team via ``support@aiven.io`` to assist you.
Not sure if we should always have this at the end of the docs, or only for important things

```suggestion
If you have any questions, please feel free to contact the support team via support@Aiven.io to assist you.
```

2022-08-17 06:47 UTC, ftisiot commented on docs/platform/howto/password-policy.rst
> +
Extra newlines to be removed?

2022-08-18 01:48 UTC, sluhur commented
> Hi @sluhur! Thanks for this! I have a question: is this an howto or more a reference/concept one?
> 
> I left some comments that needs to be addressed.
> 
> Also it would be cool to have a dedicated howto on how to reset the password. I believe it would be one of the most clicked articles :D

I can create additonal document on how to change the password. 
Where we should put this Password Policy then?

2022-08-19 07:36 UTC, ftisiot requested changes
Please check the warnings regarding the capitalization of the headings. 
I believe this should be moved under reference since it's a static reference to a policy

2022-08-19 07:36 UTC, ftisiot commented on docs/platform/howto/password-policy.rst
> +Password Policy
Please review the capitalization for the title

2022-08-23 08:18 UTC, ftisiot commented
Hi @sluhur, please check the warnings again, there's still a capitalization to fix.
Moreover if we can move this under the reference subtree it would be amazing

2022-08-23 23:13 UTC, sluhur commented
> Hi @sluhur, please check the warnings again, there's still a capitalization to fix. Moreover if we can move this under the reference subtree it would be amazing

Done

2022-08-24 06:15 UTC, ftisiot approved these changes
LGTM

2022-08-24 06:17 UTC, merged