Migrate article: Preparing for high load #1076
aiven/devportal pull request #1292
Opened 2022-08-25 03:33 UTC by sluhur

https://github.com/aiven/devportal/issues/1076

# What changed, and why it matters

2022-08-25 07:44 UTC, ftisiot requested changes
Hi @sluhur 
Thanks for this. The screenshots are showing an old version of our UI, could you please check if:
- They are really neeed
- if yes, you can create an updated version of them
We're trying to minimise screenshots since our UI is always evolving and keeping them up to date can become a huge task.
Furthemore, there's a warning in the build, can you check?

2022-08-26 02:17 UTC, sluhur commented
> Hi @sluhur Thanks for this. The screenshots are showing an old version of our UI, could you please check if:
> 
> * They are really neeed
> * if yes, you can create an updated version of them
>   We're trying to minimise screenshots since our UI is always evolving and keeping them up to date can become a huge task.
>   Furthemore, there's a warning in the build, can you check?

I've checked the screenshots and they're not really needed. I've removed them all.

2022-08-30 08:36 UTC, ftisiot requested changes
Hi @sluhur, a couple of comments to address:
* Titles: avoid the `ing` and use the present. e.g. `Preparing for high load` -> `Prepare for high load`
* Article position, is this an howto?
* There's a lot of content that is written here (e.g. Plans, upgrades, maintenance, forks) that could be just referenced to other articles with a link
* Check the links, some of the content is already moved to devportal

2022-08-30 08:37 UTC, ftisiot commented
Hi @sluhur, thanks for this, please re-check the PR description. I had to change it to add 
```
Fix #issue_number
```
If you don't prefix with `Fix`, merging the PR will **not** close the related issue

2022-09-02 07:20 UTC, ftisiot requested changes
Hi @sluhur, I believe I'm making the same content as per #1335 

I believe we need to check in depth what makes sense to be ported in devportal and how an article fits the [contributing guide](https://github.com/aiven/devportal/blob/main/CONTRIBUTING.rst)

I believe this is valuable info, but how's it different from https://github.com/aiven/devportal/pull/1335? What type of content should this be? a concept/reference/howto?

Also please take some time to port the format correctly to the devportal style, I currently see:

Notes that are not devportal notes style
Links with the link full text and not a caption
Reference to support which is unnecessary
Doing some of this thinking/work upfront during the porting would mean providing an article which is closer to be merged to devportal and therefore needing less interaction from a review point of view!

2022-09-02 07:20 UTC, ftisiot commented on _toc.yml
> -      - file: docs/platform/concepts/service-level-agreement
Why service level agreement is gone?

2022-09-13 09:44 UTC, laysauchoa commented
Hey, I was taking a look in this PR and it seems to have mixed content between HowTo and Concepts. The section is "Prepare for high load" so seems to fit in "HowTo" like "How to Prepare for High Load". However, under this section there are things like Plans etc which are not a HowTo topic. So I'd suggest to go over the topics and place it where they are more appropriate.

2022-10-12 13:58 UTC, lornajane commented
@sluhur There's some good work here, could you take a look at the requested changes, or let us know if you aren't available to work on this?

2022-10-21 08:13 UTC, ftisiot commented
@laysauchoa @lornajane: I took the great work that @sluhur already did and changed a bit the style by:
- referencing to existing other pages when needed
- adding sections as Tips/Warnings
I believe it's ready for review

2022-10-26 19:50 UTC, dewan-ahmed approved these changes
Thanks for the latest fixes @ftisiot 

LGTM

Thank you.

2022-10-26 19:50 UTC, merged