Fix #1082 Migrate article: Reacting to high load #1082
aiven/devportal pull request #1335
Opened 2022-09-01 01:36 UTC by sluhur

# What changed, and why it matters

Fix #1082

2022-09-02 07:18 UTC, ftisiot requested changes
Hi @sluhur, thanks for this! 

I believe we need to check in depth what makes sense to be ported in devportal and how an article fits the [contributing guide](https://github.com/aiven/devportal/blob/main/CONTRIBUTING.rst) 

I believe this is valuable info, but how's it different from #1292?  What type of content should this be? a concept/reference/howto?

Also please take some time to port the format correctly to the devportal style, I currently see:

* Notes that are not devportal notes style
* Links with the link full text and not a caption
* Reference to support which is unnecessary

Doing some of this thinking/work upfront during the porting would mean providing an article which is closer to be merged to devportal and therefore needing less interaction from a review point of view!

2022-09-02 07:18 UTC, ftisiot commented on _toc.yml
> -      - file: docs/platform/concepts/maintenance-window
Why is maintenance window gone?

2022-09-12 07:40 UTC, ftisiot commented
Hi @sluhur, are you planning to work on this or should I close it?

2022-10-12 13:56 UTC, lornajane commented
Closing due to inactivity; issue unassigned

2022-10-12 13:56 UTC, closed without merging