Issue #1303 - added section for poor performance after migration
aiven/devportal pull request #1360
Opened 2022-09-08 00:08 UTC by bcrisologo

#1303 issue - added a section where poor performance is experienced after migration on pg service.  Modified the formatting and some language from original article.

2022-09-09 07:10 UTC, ftisiot requested changes
Hi @bcrisologo,
Thanks for this, one small fix before it's ready to be merged

2022-09-09 07:10 UTC, ftisiot commented on docs/products/postgresql/howto/migrate-pg-dump-restore.rst
> +For more information about ``ANALYZE``, you may see the official `sql analyze <https://www.postgresql.org/docs/current/sql-analyze.html>`_ documentation.
I believe SQL should be capital :D

2022-09-09 16:09 UTC, bcrisologo commented on docs/products/postgresql/howto/migrate-pg-dump-restore.rst
> +For more information about ``ANALYZE``, you may see the official `sql analyze <https://www.postgresql.org/docs/current/sql-analyze.html>`_ documentation.
Updated :)

2022-09-12 06:45 UTC, ftisiot approved these changes
LGTM

2022-09-12 06:45 UTC, merged