Put the list of kafka connectors on the kafka connect landing page
aiven/devportal pull request #1378
Opened 2022-09-13 21:01 UTC by lornajane

# What changed, and why it matters

Definitely a work in progress, to maybe-possibly group the connectors and make a bit more of a landing page feature.

2022-09-21 11:11 UTC, ftisiot commented
I like the idea! I would probably use the cards if we can have multiple links in them to have a more compacted view (something like the image below)

![home page with cards](https://user-images.githubusercontent.com/11272743/191489487-3ec3bc5e-056c-4ce7-8193-08c26137095f.png)

2022-09-21 11:12 UTC, ftisiot commented
I believe we can move away from the current list of connectors once #1377 is merged

2022-10-06 20:03 UTC, lornajane commented
Do you mean the cards should be in two columns like the home page? Or one card per connector?

2022-10-11 09:54 UTC, ftisiot commented
I would use the same 2 column approach

2022-10-11 16:51 UTC, lornajane commented
Next question: we're linking out to the docs, but we also have some resources for each of the connectors (or most of them). Should we reconsider where we link to, and show them the Aiven examples?

2022-10-12 08:34 UTC, ftisiot commented
Yep, now that #1377 has been merged, we can change the links... let me work on this later today

2022-10-13 07:15 UTC, ftisiot commented
I moved to internal links, and added the redirect. Now we are missing:

- What to do with the `Requesting new connectors` section present in the original `list-of-connector-plugins`
- Remove the `list-of-connector-plugins` page

2022-10-19 06:41 UTC, ftisiot commented
Ready to be reviewed!

2022-10-19 07:21 UTC, harshini-rangaswamy requested changes
Some minor changes to the "Request a new connector" topic. The rest looks good.

2022-10-19 07:21 UTC, harshini-rangaswamy commented on docs/products/kafka/kafka-connect/howto/request-new-connector.rst
> +If you know about new and interesting Apache Kafka®ive connectors you'd like us to support, please send us an email to support@Aiven.io about it to help us shaping the future roadmap. We will evaluat
This "interesting Apache Kafka®ive connectors" should be "interesting Apache Kafka® connectors"?

2022-10-19 07:21 UTC, harshini-rangaswamy commented on docs/products/kafka/kafka-connect/howto/request-new-connector.rst
> +If you know about new and interesting Apache Kafka®ive connectors you'd like us to support, please send us an email to support@Aiven.io about it to help us shaping the future roadmap. We will evaluat
```suggestion
If you know about new and interesting Apache Kafka® connectors you'd like us to support, please email us at support@Aiven.io to help us shape the future roadmap. We will evaluate the requested connector and might add support for it.
```

2022-10-19 07:21 UTC, harshini-rangaswamy commented on docs/products/kafka/kafka-connect/howto/request-new-connector.rst
> +Aiven evaluation process for new Apache Kafka Connect connectors checks:
```suggestion
Aiven's evaluation process for new Apache Kafka Connect connectors checks:
```

2022-10-19 07:34 UTC, harshini-rangaswamy approved these changes
Looks good!

2022-10-19 07:35 UTC, merged