improve upgrade to OS with tf, add missing resource imports
aiven/devportal pull request #1394
Opened 2022-09-19 10:51 UTC by byashimov

# What changed, and why it matters

Adds missings required imports to use OS with TF

2022-09-20 10:40 UTC, ivan-savciuc requested changes
I think we should move it closer towards the end of the article after:

> Your Elasticsearch service has been upgraded to OpenSearch with Terraform, and the resource configuration updated to use a resource type of OpenSearch.

2022-09-20 10:40 UTC, ivan-savciuc commented on docs/products/opensearch/howto/upgrade-to-opensearch-with-terraform.rst
> +Describe and import dependent resources if exist.
I would move this to the end of the block and use the following working: 
If you have had any Elasticsearch ALCs and users, do not forget to import Opensearch counterparts to the Terraform state.

2022-09-21 13:01 UTC, ivan-savciuc commented
@dewan-ahmed can you also check this one?

2022-09-21 15:04 UTC, dewan-ahmed commented
Hi @ivan-savciuc @byashimov I'll leave the testing/validation of the steps to you. 

My suggestion would be to move this content from "OpenSearch/HowTo" to "Terraform/HowTo". The way most of our content are structured, they show how to do things using the console and then the tool-specific content are under docs/tools/<tool-name>, for example, docs/tools/terraform. 

https://docs.aiven.io/docs/products/opensearch/howto/upgrade-to-opensearch.html could have a link to this article. Check out how https://docs.aiven.io/docs/platform/howto/create_new_service.html has a note at the bottom of the article.

A minor editorial comment:

- "our Terraform provider" could be rephrased as "Aiven Provider for Terraform", the official name.

Thanks for this contribution.

2022-09-24 01:51 UTC, dewan-ahmed approved these changes
Thanks for these changes @byashimov 

LGTM.

2022-09-24 01:52 UTC, merged