Kafka connect influx sink
aiven/devportal pull request #1498
Opened 2022-10-24 14:22 UTC by ftisiot

# What changed, and why it matters

Missing InfluxDB example

2022-10-27 14:45 UTC, anelook reviewed
Couple of minor comments for now!

2022-11-03 14:16 UTC, lornajane commented
Just for clarity - has one of you seen this working, using these instructions? (I assume yes, but I want to be certain since I have an incoming question about it)

2022-11-03 15:26 UTC, anelook requested changes
Couple of typos to be fixed. But the bigger issue is the wrong parsing of JSON and "value.converter.basic.auth.credentials.source": "USER_INFO" in the console.

2022-11-03 15:26 UTC, anelook commented on docs/products/kafka/kafka-connect/howto/influx-sink.rst
> +        "connect.mongo.kcql": "select into measurements select ts, device_name, measurement from measurements",
mongo? ;)

2022-11-03 15:26 UTC, anelook commented on docs/products/kafka/kafka-connect/howto/influx-sink.rst
> +* ``"connect.mongo.kcql": "select into measurements select ts, device_name, measurement from measurements"``: the connector logic is to insert every topic message as new document into a table called
mongo?

2022-11-03 15:27 UTC, ftisiot commented
I've checked this last week, and doing an additional check now on the syntax. Seems ok apart from the problem Olena highlighted before

2022-11-10 18:52 UTC, anelook approved these changes
Thank you for adding the changes. This was quite hard to test :D Looks good to me now.

2022-11-10 18:52 UTC, merged