Help article issue821 - disable platform auth
aiven/devportal pull request #1574
Opened 2022-11-15 21:01 UTC by dewan-ahmed

# What changed, and why it matters

Help migration article to resolve https://github.com/aiven/devportal/issues/821

I left out the CLI bits from [this article](https://help.aiven.io/en/articles/5086140-disabling-platform-authentication) and pointed the reader to the [dedicated CLI docs](https://docs.aiven.io/docs/tools/cli/account/account-authentication-method.html) instead.

2022-11-17 17:09 UTC, lornajane commented
I'll try to review this soon, but can we figure out a more positive way to title this article, which is about securing an account rather than disabling anything? It's stop using your password now you have something better. But let's say that in a shorter way that is currently escaping me ...

2022-11-17 20:31 UTC, dewan-ahmed commented
The securing part is on the SAML articles and this article only talks about how to disable platform authentication if you have enabled an alternative method of authentication. I thought of **Secure Aiven platform authentication** but then we're not talking about how to secure the platform authentication. I cannot think of an appropriate title that tells exactly what article is for but I'm happy to take suggestions.

2022-11-17 20:33 UTC, dewan-ahmed commented
I also thought of "Swap password-based platform authentication" but we're not really swapping the two authentication here.

2022-11-21 10:37 UTC, ftisiot requested changes
Good content, a small suggestion for readibility

2022-11-21 10:37 UTC, ftisiot commented on docs/platform/howto/disable-platform-authentication.rst
> +1. Log in to the Aiven Console using your alternative authentication (for example, SAML) method. You must not be logged in with any open sessions using the password-based platform authentication.
Should the `You must not be logged in with any open sessions using the password-based platform authentication.` be a warning?

2022-11-29 09:53 UTC, ftisiot approved these changes
LGTM

2022-11-29 09:56 UTC, merged

2022-11-29 14:29 UTC, dewan-ahmed commented
Thanks @ftisiot for adding the entries to the migration sheet 🙏🏽

2022-11-29 14:30 UTC, ftisiot commented
:D