clickhouse: reorganize info architecture for clickhouse section
aiven/devportal pull request #1625
Opened 2022-12-07 16:57 UTC by wojcik-dorota

https://aiven.atlassian.net/browse/DOC-69

2022-12-07 17:22 UTC, harshini-rangaswamy requested changes
At first glance, it looks great. Just found one page where content is not loading correctly.

2022-12-07 17:22 UTC, harshini-rangaswamy commented on docs/products/clickhouse/howto/get-started/connect-to-service.rst
> +.. include:: /docs/products/clickhouse/howto/connect.rst
Looks like this is not loading the content from connect.rst file as expected. I see a blank screen.

2022-12-07 19:36 UTC, lornajane commented
This feels like it could be a high-risk pull request, in particular there are a lot of renames that will break existing URLs and we are actively trying to avoid carrying a large burden of redirects so we should consider what our options are to achieve the same things. I would also like us to take advice before following the content-duplication pattern introduced by the includes, I'm not sure about the impacts of this either from a content performance or a user experience point of view. Once this is ready to come out of draft, I'd like to be one of the reviewers before we merge, please.

2022-12-08 13:05 UTC, anelook commented
I agree with @lornajane. 
One more comment - the .toc tree can be changed according to our desires without renaming and moving files. So, in case we do want to experiment with tree structure, we can still keep files and their locations intact, but just use .toc to put them into desirable flow. This will avoid the need for redirects and also allows us to change the tree structure painlessly multiple times.

2022-12-08 13:37 UTC, dewan-ahmed commented
I strongly agree with @lornajane on the includes pattern. I know I've reviewed and merged a few cookbook recipes for ClickHouse that had the `includes` but I was pretty uncomfortable doing so. The main reason is that this pattern creates a lot of hidden dependencies and changing one file creates a cascading effect. If possible, let's stick to :doc: and :ref: please.

2022-12-08 13:54 UTC, wojcik-dorota commented
> 

@dewan-ahmed @lornajane , thank you for your feedback. Please confirm I understand it correctly: If I need to reuse an article somewhere else than its original location, instead of creating a new file in the target location and using `include` directive inside it, I actually need to create a new file in the target location and build it as an actual document of its own with just one sentence including the :doc: link to the original article. This would generate a number of articles including one link each just to redirect the user. Or how else would you recommend to handle that?

2022-12-08 14:07 UTC, wojcik-dorota commented
@sbijjal @jkowall , @divdby0 please have a look at the comments from DevRels colleagues. With this issues open we might have some challenges to be ready with restructuring the ClickHouse docs by GA.

2022-12-08 14:51 UTC, lornajane commented
My main concern with this approach to the includes is that we specifically discussed that we would signpost content, rather than duplicating it. This pull request takes exactly the opposite approach and puts the same content under multiple URLs. This could be confusing to the user, and may also be a problem for SEO - which is why we have a guideline to avoid this.

2022-12-08 14:55 UTC, lornajane commented
@wojcik-dorota Please also mention if the reviews you are requesting are particularly timely, I see the comment about something going GA, but most of the reviewers here won't have that context. It is also fine to use internal channels for that discussion rather than the public repository thread if appropriate.

2022-12-08 14:58 UTC, wojcik-dorota commented
> 

@lornajane here's the discussion is opened for this PR with the timeline specified  https://aiven-io.slack.com/archives/C01T6379FBQ/p1670499770936199

2022-12-08 18:29 UTC, anelook commented
@wojcik-dorota, what I meant regarding **_toc.yml** file, is when you look at https://docs.aiven.io/docs/products/kafka/howto/connect-with-python.html, it is located in howTo folder, however in the menu tree on the left it is under **Code samples**. 

If you look at **_toc.yml** you'll see something like this:

```
entries:
          - file: docs/products/mysql/howto/list-code-samples
            entries:
              - file: docs/products/mysql/howto/connect-from-cli
              - file: docs/products/mysql/howto/connect-with-python
              - file: docs/products/mysql/howto/connect-using-mysqlx-with-python
              - file: docs/products/mysql/howto/connect-with-java
              - file: docs/products/mysql/howto/connect-with-php
```

2022-12-09 14:31 UTC, closed without merging

2022-12-09 14:32 UTC, wojcik-dorota commented
This one is followed up on and fixed via https://github.com/aiven/devportal/pull/1629