1685 migrate aiven for mysql remote replica
aiven/devportal pull request #1688
Opened 2023-01-10 20:46 UTC by deanholbrough

# What changed, and why it matters

Migrated the Intercom Help Article [Aiven for MySQL Remote Replica](https://app.intercom.com/a/apps/reo7593q/articles/articles/4948943/show) to https://docs.aiven.io

Added the article to Products > MySQL > HowTo > Create MySQL Remote Replica TOC structure

2023-01-11 08:06 UTC, ftisiot commented
Hi @deanholbrough ,
Thanks for the contribution but the build is failing, can you please check in the `Files Changed` tab what's wrong?

2023-02-07 12:08 UTC, wojcik-dorota requested changes

2023-02-07 12:08 UTC, wojcik-dorota commented on docs/products/mysql/howto/create-remote-replica.rst
> +
Please add section title "Create a remote replica" or similar.

2023-02-07 12:08 UTC, wojcik-dorota commented on docs/products/mysql/howto/create-remote-replica.rst
> +Here are the steps to provision remote replica
Here are the steps to provision remote replica => Take the following steps to provision a remote replica:

2023-02-07 12:08 UTC, wojcik-dorota commented on docs/products/mysql/howto/create-remote-replica.rst
> +
Please add a full stop at the end of each step.

2023-02-07 12:08 UTC, wojcik-dorota commented on docs/products/mysql/howto/create-remote-replica.rst
> +3. Click  the "Create a read replica" button
Click  the "Create a read replica" button => `Select **Create a read replica**.`

2023-02-07 12:08 UTC, wojcik-dorota commented on docs/products/mysql/howto/create-remote-replica.rst
> +2. Navigate to the MySQL instances for which you wish to create a remote replica
instances => services?

2023-02-07 12:08 UTC, wojcik-dorota commented on docs/products/mysql/howto/create-remote-replica.rst
> +1. Login into the Aiven console using your credentials
``Log in to the `Aiven console <https://console.aiven.io/>`_  using your credentials.``

2023-02-07 12:08 UTC, wojcik-dorota commented on docs/products/mysql/howto/create-remote-replica.rst
> +5. Click "Create"
``Select **Create**.``

2023-02-07 12:08 UTC, wojcik-dorota commented on docs/products/mysql/howto/create-remote-replica.rst
> +That's it. You will see the read replica being created and listed as any other Aiven service on the Services page on the console.
```
.. topic:: Result

   You can see the read replica being created and listed as any other Aiven service on the **Services** page in the console.
```

2023-03-16 08:21 UTC, wojcik-dorota commented
@deanholbrough , hope you dont mind I've created a new PR (https://github.com/aiven/devportal/pull/1814) for this one - including all your content and with my comments already implemented. Hope this way I can save us some time delivering  this article.

2023-03-16 08:21 UTC, closed without merging