cassandra: how to disable cross-cluster replication
aiven/devportal pull request #1734
Opened 2023-01-30 16:25 UTC by wojcik-dorota

https://aiven.atlassian.net/browse/DOC-166

This is a part of the PR set covering the cross-cluster replication feature for Aiven for Apache Cassandra.
By the time they are merged, I'm not able to cross-reference between them, which is obviously needed. When all the four articles are merged, I'll include relevant links in all of them so that the user is properly guided thru the whole thing.

- CCR concept https://github.com/aiven/devportal/pull/1759
- Enable CCR https://github.com/aiven/devportal/pull/1732
- Manage CCR https://github.com/aiven/devportal/pull/1741

2023-02-02 14:23 UTC, dmitry-potepalov requested changes
overall ok, some concerns about the phrasing in the comments

2023-02-02 14:23 UTC, dmitry-potepalov commented on docs/products/cassandra/howto/disable-cross-cluster-replication.rst
> +      As soon as you split the cluster, the two services constituting the CCR pair become independent. It's not possible to recreate the CCR pair with the same service as a replica. You can select an
> You can select any other Aiven for Cassandra service for that purpose.

not quite that, you can:
* create 2 new services with CCR
* given an existing service, create a new one to do CCR with the existing service

but you cannot:
* given 2 existing services, enable CCR between them.

The quoted sentence sounds like "you cannot re-link the services that you just separated, but you can re-link one of them with another existing service" which is not the case

2023-02-02 14:23 UTC, dmitry-potepalov commented on docs/products/cassandra/howto/disable-cross-cluster-replication.rst
> +      As soon as you delete the replica service, CCR gets disabled for your service that is now connected to the replica service for CCR purposes.
> for your service that is now connected to the replica service for CCR purposes.

I think it's no longer connected to anything, after you deleted the other one?... I'd just end it at "CCR gets disabled" or maybe "your data is no longer replicated between regions"

2023-02-02 14:23 UTC, dmitry-potepalov commented on docs/products/cassandra/howto/disable-cross-cluster-replication.rst
> +You can disable CCR for your Aiven for Apache Cassandra service(s) by calling the `terminate a service <https://api.aiven.io/doc/#tag/Service/operation/ServiceDelete>`_ endpoint to delete one of the
is it called "terminate endpoint" anywhere? it is ServiceDelete, maybe the "delete service endpoint"?

2023-02-03 15:54 UTC, wojcik-dorota commented on docs/products/cassandra/howto/disable-cross-cluster-replication.rst
> +When you enable CCR for your service, you connect it to another service (replica service), which results in creating a CCR pair of services. You can disable CCR for your service either by splitting t
if not replica service, how else can we name them? I mean the service on which you enable CCR and the other service you connect to for replication purposes? We could use some short terms for these guys. It's not easy for me to come up with relevant names: parent/primary/source/origin service vs child/secondary/sink/target service ?

2023-02-03 16:12 UTC, wojcik-dorota commented on docs/products/cassandra/howto/disable-cross-cluster-replication.rst
> +When you enable CCR for your service, you connect it to another service (replica service), which results in creating a CCR pair of services. You can disable CCR for your service either by splitting t
@divdby0 , any ideas how to call the two service that build the CCR pair?

2023-02-03 16:48 UTC, divdby0 commented on docs/products/cassandra/howto/disable-cross-cluster-replication.rst
> +When you enable CCR for your service, you connect it to another service (replica service), which results in creating a CCR pair of services. You can disable CCR for your service either by splitting t
@wojcik-dorota In the Cassandra realm both parties are equals. I might suggest using _pairs_, _peers_ or just _services_. Although technically accurate, I agree with @dmitry-potepalov that using the term _replicas_ makes a fuzzy connotation to the PostgreSQL read-only replicas. Alternatively, we might get away with without using an explict term. i.e.: _When you enable CCR, your services get cross replicated with each other._

2023-02-03 18:37 UTC, wojcik-dorota commented on docs/products/cassandra/howto/disable-cross-cluster-replication.rst
> +When you enable CCR for your service, you connect it to another service (replica service), which results in creating a CCR pair of services. You can disable CCR for your service either by splitting t
thx, will update accordingly :-)

2023-02-13 13:48 UTC, dmitry-potepalov reviewed
Overall LGTM, left some comments

2023-02-13 13:48 UTC, dmitry-potepalov commented on docs/products/cassandra/howto/disable-cross-cluster-replication.rst
> +      As soon as you split the cluster, the two services constituting the CCR pair become independent. It's not possible to recreate the CCR pair connecting back to the same service. To enable CCR on
Should we include this warning in the About chapter as well?... on the one hand, it doesn't describe the splitting in detail, on the other hand - one might glance through the About chapter, nod and then proceed to click in the Console without ever scrolling down to see the warning :thinking:

2023-02-13 13:48 UTC, dmitry-potepalov commented on docs/products/cassandra/howto/disable-cross-cluster-replication.rst
> +* Depending on the method you choose to use for enabling CCR
"for enabling CCR" -> "for disabling CCR"

2023-02-13 13:48 UTC, dmitry-potepalov commented on docs/products/cassandra/howto/disable-cross-cluster-replication.rst
> +   You've disabled CCR on your service by deleting the service used as a sink for replicated data.
> used as a sink for replicated data

hints that the other service is a source, meaning that the other service is somehow different; maybe "by deleting one of the peer services in a CCR service pair"?

2023-02-16 16:42 UTC, alanfranz approved these changes
LGTM

2023-02-21 10:44 UTC, dmitry-potepalov approved these changes
LGTM

2023-02-24 17:51 UTC, divdby0 approved these changes

2023-02-28 15:54 UTC, merged