Make links descriptive
aiven/devportal pull request #1794
Opened 2023-02-27 14:37 UTC by staceysalamon-aiven

# What changed, and why it matters
Made links on the docs homepage descriptive for better accessibility and SEO. Some other minor changes to tool descriptions and other microcopy. 

Resolves: #1276

2023-02-28 16:32 UTC, harshini-rangaswamy requested changes
A few minor things in this PR, 

- could you right-align the links to "Aiven Console Overview and Aiven CLI Quickstart (should Overview and Quickstart be lowercase? )

- Automation section - make the boxes similar in size to the above section for uniformity. 

![image](https://user-images.githubusercontent.com/108724024/221915896-25f55e43-5188-48bf-941f-80261933085d.png)

I- Not sure about how feasible this is, but it would be nice to align the links, for example, "Learn about M3" and "Learn about MySQL" 

![image](https://user-images.githubusercontent.com/108724024/221916401-fa84e1f8-3fd2-4075-9da1-ff92831e13ed.png)

2023-02-28 16:34 UTC, staceysalamon-aiven commented
> A few minor things in this PR,
> 
> * could you right-align the links to "Aiven Console Overview and Aiven CLI Quickstart (should Overview and Quickstart be lowercase? )
> * Automation section - make the boxes similar in size to the above section for uniformity.
> 
> ![image](https://user-images.githubusercontent.com/108724024/221915896-25f55e43-5188-48bf-941f-80261933085d.png)
> 
> * Not sure about how feasible this is, but it would be nice to align the links, for example, "Learn about M3" and "Learn about MySQL"
> 
> ![image](https://user-images.githubusercontent.com/108724024/221916401-fa84e1f8-3fd2-4075-9da1-ff92831e13ed.png)

I changed the alignment to keep everything from looking the same; same with the automation tools. I wanted to have a little different look/weight because otherwise I think everything on the page just looks the same.

I'm not aware of a way to manually align the links, but I do think the copy for services should be updated, which could help with these being a little more aligned (though, that will depend on the device).

2023-03-01 03:08 UTC, harshini-rangaswamy commented
> I changed the alignment to keep everything from looking the same; same with the automation tools. I wanted to have a little different look/weight because otherwise I think everything on the page just looks the same.
> 
> I'm not aware of a way to manually align the links, but I do think the copy for services should be updated, which could help with these being a little more aligned (though, that will depend on the device).

I think having some degree of symmetry in the design is visually appealing. While scrolling through the page, there is a sense of disconnection in its overall look and feel. For instance, varying alignment of links, such as the center alignment of "Aiven Console overview" and "Aiven CLI quickstart", compared to the rest that is right-aligned. (this may be just my perception, and others may view it differently). 
The points may seem trivial since it's uncertain whether users browse the page or use the search function to find information.
Maybe, we could push the changes and see if we get any feedback?

2023-03-01 03:10 UTC, harshini-rangaswamy approved these changes

2023-03-01 03:10 UTC, merged