Enable OpenSearch Security [DOC-241]
aiven/devportal pull request #1840
Opened 2023-03-29 15:03 UTC by harshini-rangaswamy

# What changed, and why it matters

OpenSearch Security content
 - About OS security, Access control in Aiven 
 - How to enable access control via console

https://aiven.atlassian.net/browse/DOC-241

2023-04-02 16:22 UTC, harshini-rangaswamy commented on docs/products/opensearch/howto/enable-opensearch-security.rst
> +* OpenSearch Security management cannot be disabled once enabled. Therefore, ensure that you thoroughly understand the security features and implications before proceeding.
Fixed

2023-04-02 16:22 UTC, harshini-rangaswamy commented on docs/products/opensearch/concepts/os-security.rst
> +OpenSearch Security management changes and impacts
Fixed

2023-04-02 16:22 UTC, harshini-rangaswamy commented on docs/products/opensearch/concepts/os-security.rst
> +* All user authentication and access control will be managed through the OpenSearch security Dashboard or OpenSearch Security API. You have the ability to add or remove users from pre-generated roles
Fixed

2023-04-02 16:22 UTC, harshini-rangaswamy commented on docs/products/opensearch/concepts/access_control.rst
> +Another way to manage user accounts, access control, roles, and permissions for your Aiven for OpenSearch® service is by :doc:`enabling OpenSearch® Security management <../howto/enable-opensearch-sec
Fixed

2023-04-05 06:09 UTC, mteiste commented on docs/products/opensearch/concepts/os-security.rst
> +* Aiven's internal users and their permissions/roles, which are necessary for managing and operating the service, are hidden and reserved from customer view and modification.
This is correct, they are hidden, but maybe remove this as a separate point and "include" it in the previous one (maybe "but some roles..." to " but users and roles essential for managing and operating the service cannot be modified".

2023-04-05 06:11 UTC, mteiste requested changes
I would hold off merging this yet. Most likely all the roles/definitions that mention aiven are going to be changed to something more generic (to cover the oem situation).

2023-05-05 12:46 UTC, hoang-vo approved these changes
Looking good now  👍

2023-05-05 13:35 UTC, merged