Slightly clearer wording on the marketplace migration process
aiven/devportal pull request #1849
Opened 2023-04-06 10:18 UTC by kevinbowman-aiven

# What changed, and why it matters

Feedback from customers using this process has led to needing slightly clearer wording on which IDs they need to send us.

2023-04-14 14:56 UTC, staceysalamon-aiven requested changes
Thanks for this! We have moved away from using the term "account" to avoid confusion with the recent changes from accounts to organizations/organizational units. I'm not certain how this looks in the GCP Console, so I have added a couple of questions in the comments. Thanks!

2023-04-14 14:56 UTC, staceysalamon-aiven commented on docs/platform/howto/move-to-gcp-marketplace-billing.rst
> +Follow the steps to :doc:`set up Google Cloud Platform Marketplace for Aiven Services <billing-google-cloud-platform-marketplace-subscription>`.  This will create a new account, which is where your p
Should this read, "This will create a new organization" since we use that term now instead of "accounts"?

2023-04-14 14:56 UTC, staceysalamon-aiven commented on docs/platform/howto/move-to-gcp-marketplace-billing.rst
> +**From your new Aiven account with the GCP marketplace subscription:**
Similar to the comment above, I'm not sure if this is the right term to use.

2023-04-14 15:06 UTC, kevinbowman-aiven commented
Thanks @staceysalamon-aiven , I've pushed a change to update to use "organization" terminology.

2023-04-17 08:01 UTC, staceysalamon-aiven approved these changes
Thanks! LGTM

2023-04-17 08:01 UTC, merged