Add FusionAuth SAML integration guide
aiven/devportal pull request #1860
Opened 2023-04-12 13:43 UTC by vcampitelli

Following [Aiven guidelines](https://github.com/aiven/devportal/blob/main/CONTRIBUTING.rst#howto-article-template) to create an article demonstrating how to use [FusionAuth](https://fusionauth.io) as the IdP via SAML.

2023-05-12 13:55 UTC, vcampitelli commented
Hi there, I've rebased the branch and added some missing words to vale's dict. Thanks for the heads up!

2023-06-14 11:42 UTC, staceysalamon-aiven requested changes
Thank you @vcampitelli for writing up these instructions! I've made suggestions based on our style guide and to more closely match the other docs. Any questions, let me know!

2023-06-14 11:42 UTC, staceysalamon-aiven commented on docs/platform/howto/saml/setup-saml-fusionauth.rst
> +Testing
```suggestion
```

2023-06-14 11:42 UTC, staceysalamon-aiven commented on docs/platform/howto/saml/setup-saml-fusionauth.rst
> +Open the Signup URL you copied above in an incognito tab or using another browser. You’ll reach the signup page below.
```suggestion
```

2023-06-14 11:42 UTC, staceysalamon-aiven commented on docs/platform/howto/saml/setup-saml-fusionauth.rst
> +.. image:: /images/platform/howto/saml/fusionauth/login-sso.png
```suggestion
```

2023-06-14 11:42 UTC, staceysalamon-aiven commented on docs/platform/howto/saml/setup-saml-fusionauth.rst
> +   :alt: Logging in to Aiven.
```suggestion```

2023-06-14 11:42 UTC, staceysalamon-aiven commented on docs/platform/howto/saml/setup-saml-fusionauth.rst
> +Click on **Sign up with FusionAuth**, which will redirect you to the FusionAuth login page. Fill in your credentials and submit the form to be taken back to the Aiven console, already logged in and p
```suggestion
```

2023-06-14 11:42 UTC, staceysalamon-aiven commented on docs/platform/howto/saml/setup-saml-fusionauth.rst
> +-------
```suggestion
```

2023-06-14 11:42 UTC, staceysalamon-aiven commented on docs/platform/howto/saml/setup-saml-fusionauth.rst
> +Testing
I don't think the testing section or the screenshot is needed here.

2023-07-10 14:15 UTC, vcampitelli commented on docs/platform/howto/saml/setup-saml-fusionauth.rst
> +Now that your application is ready, clone `this GitHub repository <https://github.com/FusionAuth/fusionauth-example-scripts>`__ and execute the script located in ``rsa-certificate``.
Yes, I've renamed it and forgot to change it here. Thanks!

2023-07-10 18:44 UTC, vcampitelli commented
Hi @staceysalamon-aiven , thank you for reviewing this! I've applied your suggestions and made the other changes. Please let me know if there is anything else!

2023-07-10 19:50 UTC, staceysalamon-aiven commented
> Hi @staceysalamon-aiven , thank you for reviewing this! I've applied your suggestions and made the other changes. Please let me know if there is anything else!

Thanks for doing that! There's an error on line 59 that I think is due to the following lines not being indented?

2023-07-11 00:33 UTC, vcampitelli commented
Hmm that was strange because it compiled well with `make livehtml`.. But it's fixed! Thanks!

2023-07-11 07:02 UTC, staceysalamon-aiven approved these changes
Looks good! Thanks again for your contribution!

2023-07-11 07:03 UTC, merged