SUP-639: Briefly describe Refresh VPC connections function
aiven/devportal pull request #1939
Opened 2023-06-06 20:26 UTC by bcrisologo

# What changed, and why it matters

We have a "Refresh VPC connections" button available inside the VPC Peering connection ID that has no documentation available.

![image](https://github.com/aiven/devportal/assets/10273586/18d1a64b-539d-4731-85d1-63e583044a18)

I've inquired about this internally and it seems this button functionality is helpful for changes done on the externally VPC peered hosts (i.e. firewall changes) in the event that there's connection issues after changes were made on the externally peered host(s).

2023-06-15 10:13 UTC, wojcik-dorota requested changes

2023-06-15 10:13 UTC, wojcik-dorota commented on docs/platform/howto/manage-vpc-peering.rst
> +If there have been network changes that were made on VPC peered hosts external from Aiven, it can cause issues with routing to your Aiven services hosted in a VPC.  In such scenarios, you can follow
```
Any network changes to VPC peered hosts external from Aiven can cause issues with routing to your Aiven services hosted in a VPC. To troubleshoot such issues, take the following steps:
```

2023-06-15 10:13 UTC, wojcik-dorota commented on docs/platform/howto/manage-vpc-peering.rst
> +Performing the above will have the platform check the VPC peering connection and rebuild the peering connection state if there are any changes detected.
```
As a result, the platform checks the VPC peering connection and rebuilds the peering connection state if there are any changes detected.
```

2023-06-15 10:13 UTC, wojcik-dorota commented on docs/platform/howto/manage-vpc-peering.rst
> +1. In the Aiven console, click **VPC**.
```
1. In `Aiven Console <https://console.aiven.io/>`_, select **VPC**.
```

2023-06-15 10:13 UTC, wojcik-dorota commented on docs/platform/howto/manage-vpc-peering.rst
> +3. Click **Refresh VPC connections** button.
```
3. Select **Refresh VPC connections**.
```

2023-06-15 10:13 UTC, wojcik-dorota commented on docs/platform/howto/manage-vpc-peering.rst
> +2. Locate the VPC ID that is affected and click on the appropriate ID under **Internal ID** column.
```
2. Find the ID of the affected VPC and select it from the **Internal ID** column.
```

2023-06-20 17:31 UTC, bcrisologo commented
Let me know if the changes look good @wojcik-dorota 🙂

2023-06-21 08:05 UTC, wojcik-dorota approved these changes

2023-06-21 08:06 UTC, merged