Add instructions for managing org users
aiven/devportal pull request #1941
Opened 2023-06-07 15:13 UTC by staceysalamon-aiven

# What changed, and why it matters
In an upcoming release it will be possible to add users directly to an organization to control their access to its units and projects. These instructions cover inviting and removing users from orgs.

2023-06-14 10:55 UTC, rsalevsky commented on docs/platform/howto/manage-org-users.rst
> +    Organization users are available as a :doc:`feature preview </docs/platform/howto/feature-preview>`.
Can we add a sentence that the feature preview has enabled? Just to avoid support tickets that the menu item is not visible.

2023-06-14 10:56 UTC, rsalevsky requested changes

2023-06-14 10:56 UTC, rsalevsky commented on docs/platform/howto/manage-org-users.rst
> +#. To automatically add these users to user groups, switch the toggle to **Yes** and select the groups.
This part doesn't exist yet.

2023-06-14 10:56 UTC, rsalevsky commented on docs/platform/howto/manage-org-users.rst
> +#. Confirm you want to remove the user by clicking **Remove user**.
Let's add a sentence that the user will be removed from all teams and projects and will have no longer access to any resource in the Org.

2023-06-14 13:16 UTC, rsalevsky approved these changes

2023-06-28 08:47 UTC, harshini-rangaswamy approved these changes
LGTM!

2023-06-28 08:47 UTC, merged