Update console overview for recent changes
aiven/devportal pull request #1954
Opened 2023-06-14 14:05 UTC by staceysalamon-aiven

# What changed, and why it matters
The console overview article has been updated to reflect the current state after several changes to the UI and admin, billing, and other functionality. 

Relies on changes made in #1942.

2023-06-14 14:40 UTC, rsalevsky requested changes

2023-06-14 14:40 UTC, rsalevsky commented on docs/tools/aiven-console.rst
> +To navigate between different projects or view all projects click the **Projects** drop-down menu. Selecting a project opens the **Services** page with a list of all services in that project. Here yo
We should add a note here which mentions that only projects which belong to the current Org / Unit are displayed. So it's not all projects you have access to.

2023-06-14 14:41 UTC, rsalevsky commented on docs/tools/aiven-console.rst
>  - :doc:`Generating authentication tokens </docs/platform/concepts/authentication-tokens>`
Tokens are on a different page in the user profile.

2023-06-15 12:14 UTC, staceysalamon-aiven commented
#1942 needs to be merged before this and after rebasing the errors will be fixed.

2023-07-21 13:57 UTC, rsalevsky approved these changes

2023-07-21 14:43 UTC, merged