platform: temporary add beta as a counterpart to limited availability
aiven/devportal pull request #2058
Opened 2023-08-01 18:50 UTC by wojcik-dorota

Although term "beta" is being removed now from the product lifecycle, it has been agreed that at least in the BYOC copy we keep "beta" by Organizations' GA, when the beta label will be removed.

Consequently, there is discrepancy in the product lifecycle naming between what we ('re gonna) have in the BYOC copy and what we have in the documentation.

* [In the doc](https://docs.aiven.io/docs/platform/concepts/beta_services#limited-availability), we have already updated the terminology and we use "limited availability - early availability - general availability" (no "beta").
* In the BYOC copy, we still use "beta" for "limited availability". The banner informing the users about the feature being in the beta version redirects them to [the doc](https://docs.aiven.io/docs/platform/concepts/beta_services#limited-availability) that already includes the new naming (so instead of finding "beta" over there, the users will find "limited availability").

This might be confusing and raise questions. This PR is to walk around this issue by adding the "beta" terms next to the "limited availability" instances in the doc so that the users, when redirected from the banner in the console to the doc, are aware that the limited availability is a counterpart of the beta.

This additional beta annotation in the doc will be removed at Organizations' GA, when the beta label is also gone from the console.

2023-08-01 19:14 UTC, bobkrygowski-Aiven commented
Original: The limited availability stage is an initial release that customers can try out. If you are interested in trying a service or feature in this stage, contact the sales team at [sales@Aiven.io](mailto:sales%40Aiven.io).

Proposed: The limited availability stage is an initial release of new functionality that customers can try, in private, by invitation only.  If you are interested in trying a service or feature in this stage, contact the sales team at [sales@Aiven.io](mailto:sales%40Aiven.io).

2023-08-01 19:15 UTC, bobkrygowski-Aiven commented
Everything else looks good to me.

2023-08-01 19:19 UTC, bobkrygowski-Aiven requested changes
Thanks Dorota, looks good.  I left a few comments.

2023-08-01 19:19 UTC, bobkrygowski-Aiven commented on docs/platform/concepts/beta_services.rst
> +The limited availability (beta) stage is an initial release that customers can try out. If you are interested in trying a service or feature in this stage, contact the sales team at sales@Aiven.io.
The limited availability (beta) stage is an initial, private release that customers can try out by invitation only.  If you are interested in trying a service or feature in this stage, contact the sales team at sales@Aiven.io.

A couple of minor changes here.

2023-08-01 19:19 UTC, bobkrygowski-Aiven commented on docs/platform/concepts/beta_services.rst
> +Before general availability, the lifecycle of new services and features includes a limited availability (beta) stage and an early availability stage.
limited availability (private beta) stage and an early availability (public beta) stage.

2023-08-02 07:05 UTC, harshini-rangaswamy approved these changes
This makes sense. It also can be beneficial for customers/users familiar with what beta versions entail.

2023-08-02 08:28 UTC, rsalevsky approved these changes
LGTM

2023-08-02 09:58 UTC, merged