Issue 2083 pg get db, table, index size
aiven/devportal pull request #2086
Opened 2023-08-10 04:59 UTC by jorgeuribe-aiven

# What changed, and why it matters
It would be useful to have an Aiven doc for reference when service user ask about disk usage in PG. 

fixes https://github.com/aiven/devportal/issues/2083

2023-08-14 12:23 UTC, wojcik-dorota commented
@jorgeuribe-aiven thank you for adding this content! I'll be happy to review it if you don't mind. I've noticed Cloudflare deployment didn't work for this PR and the preview URL is not available. Could you please try to rebase so that we check if the deployment works this time? Thanks again :-)

2023-08-14 12:32 UTC, wojcik-dorota commented
Please add this article to
- https://github.com/aiven/devportal/blob/main/docs/products/postgresql/howto.rst 
- https://github.com/aiven/devportal/blob/main/docs/products/postgresql/howto/list-dba-tasks.rst
Thank you!

2023-08-14 13:09 UTC, wojcik-dorota commented
Please introduce all code blocks using
```
.. code-block:: bash
```
instead ``::``
Use a relevant programming language ofc.

2023-08-14 14:31 UTC, wojcik-dorota requested changes

2023-08-14 14:31 UTC, wojcik-dorota commented on docs/products/postgresql/howto/pg-object-size.rst
> +The database size can be retrieved using the following psql command ``\l+ [ pattern ]``::
```
Retrieve the database size using either the ``\l+ [ pattern ]`` command `` or the the ``pg_database_size`` function.

Use the ``\l+ [ pattern ]`` command
'''''''''''''''''''''''''''''''''''
```

2023-08-14 14:31 UTC, wojcik-dorota commented on docs/products/postgresql/howto/pg-object-size.rst
> +An alternative to get the database size is to use the ``pg_database_size`` function::
```
Use the ``pg_database_size`` function
'''''''''''''''''''''''''''''''''''''
```

2023-08-14 14:31 UTC, wojcik-dorota commented on docs/products/postgresql/howto/pg-object-size.rst
> +The function ``pg_indexes_size`` can be used to query the size for **all the indexes** that belong to a table::
```
Use the ``pg_indexes_size`` function
''''''''''''''''''''''''''''''''''''

The ``pg_indexes_size`` function can be used to query the size for all the indexes that belong to a table.
```

2023-08-14 14:31 UTC, wojcik-dorota commented on docs/products/postgresql/howto/pg-object-size.rst
> +Get table and its indexes size
Get a size for a table and its indices

2023-08-14 14:31 UTC, wojcik-dorota commented on docs/products/postgresql/howto/pg-object-size.rst
> +It is possible to get the disk usage for a table and its corresponding indexes, the function ``pg_total_relation_size`` computes the total disk space used by the specified table, including all indexe
To get disk space usage for a table and its indexes, you can use the ``pg_total_relation_size`` function, which computes the total disk space used by the table, all its indices, and TOAST data.

2023-08-14 14:31 UTC, wojcik-dorota commented on docs/products/postgresql/howto/pg-object-size.rst
> +    `Database Object Management Functions <https://www.postgresql.org/docs/current/functions-admin.html#FUNCTIONS-ADMIN-DBOBJECT>`_
```
.. seealso::

   * `PostgreSQL interactive terminal <https://www.postgresql.org/docs/15/app-psql.html>`_
   * `Database Object Management Functions <https://www.postgresql.org/docs/current/functions-admin.html#FUNCTIONS-ADMIN-DBOBJECT>`_
```

2023-08-14 14:31 UTC, wojcik-dorota commented on docs/products/postgresql/howto/pg-object-size.rst
> +    WAL files will also contribute to the service disk usage for additional information see: :doc:`../concepts/pg-disk-usage`.
```
WAL files also contribute to the service disk usage. For more information, check :doc:`About PostgreSQL® disk usage </docs/products/postgresql/concepts/pg-disk-usage>`.
```

2023-08-14 14:31 UTC, wojcik-dorota commented on docs/products/postgresql/howto/pg-object-size.rst
> +    It is not recommended to use the ``pg_relation_size`` function as it computes the disk space used by one “fork” of the specified relation. (Note that for most purposes it is more convenient to us
```
It is not recommended to use the ``pg_relation_size`` function as it computes the disk space used by only one fork of the relation. To get the total size of all the relation's forks, use higher-level functions ``pg_total_relation_size`` or ``pg_table_size``.
```

2023-08-15 06:58 UTC, jorgeuribe-aiven commented
@wojcik-dorota I have applied the changes you suggested and merged the main branch, so preview should be available.

2023-08-16 09:16 UTC, wojcik-dorota commented
> @wojcik-dorota I have applied the changes you suggested and merged the main branch, so preview should be available.

@jorgeuribe-aiven looks great! I understand this has been a significant effort and thank you for that!
One last missing thing is: Please add this article to

- https://github.com/aiven/devportal/blob/main/docs/products/postgresql/howto.rst
- https://github.com/aiven/devportal/blob/main/docs/products/postgresql/howto/list-dba-tasks.rst

so that it's visible in relevant index/listing/ToC pages.

2023-08-17 08:44 UTC, wojcik-dorota approved these changes
LGTM! Thank you :-)

2023-08-18 01:43 UTC, merged