Redirect cookbook
aiven/devportal pull request #2114
Opened 2023-08-25 11:04 UTC by celestehorgan

# What changed, and why it matters

This PR is is the "mechanical" parts of migrating the Aiven Terraform Cookbook recipes to the developer center. It does the following: 

1. Redirects the URLs for all Terraform Cookbook pages to developer center pages
2. Removes the Terraform Cookbook from toc.yml
3. Removes the files for the cookbook

# Part 1 of 2 

An additional PR will be created to manually correct links to the terraform cookbook that appear elsewhere in the docs, as redirects tend to lower or SEO :) 

# Do not merge yet

Hold on this PR until the pages in Sanity CMS are approved and published. Then, we will test the redirects manually to ensure (hope?) that they don't break. The redirects won't work until the page is published so this build won't pass until that happens anyways.

Submitting this as not-a-draft because I want the build to run (and fail if required).

2023-08-28 08:08 UTC, staceysalamon-aiven requested changes
Just a couple of very minor changes. Thanks for doing this!

2023-08-28 08:08 UTC, staceysalamon-aiven commented on docs/products/clickhouse/howto/manage-users-roles.rst
> +--------------
```suggestion
------------------------
```

2023-08-28 08:08 UTC, staceysalamon-aiven commented on docs/products/clickhouse/howto/manage-users-roles.rst
> +You can also manage user roles and access using the `Aiven Terraform Provider</docs/tools/terraform>`. See `The Aiven Terraform Provider Cookbook recipe: Manage user privileges for Aiven for Clickhou
```suggestion
You can also manage user roles and access using the `Aiven Provider for Terraform </docs/tools/terraform>`. Try the Aiven Terraform Provider Cookbook recipe, Manage user privileges for Aiven for Clickhouse® services using Terraform<https://aiven.io/developer/manage-user-privileges-clickhouse-terraform>`.
```

2023-08-28 11:19 UTC, celestehorgan commented
So the Build HTML check is still failing, but now it's failing because it can't find certain links. I'm going to publish the files in their new locations and rerun the builds and see if that addresses the issue.

2023-08-30 11:38 UTC, staceysalamon-aiven approved these changes
LGTM

2023-08-30 11:38 UTC, merged