Content and steps for OpenID Connect
aiven/devportal pull request #2120
Opened 2023-08-30 07:59 UTC by harshini-rangaswamy

# What changed, and why it matters

Aiven for OpenSearch with OpenSearch Security Management now supports OpenID connect. This PR includes an overview and the steps to enable OIDC for Aiven for OpenSearch.

2023-08-30 08:57 UTC, hoang-vo reviewed
Looks good from my side but we need to wait for @mteiste approvals

2023-08-30 11:06 UTC, mteiste requested changes

2023-08-30 11:06 UTC, mteiste commented on docs/products/opensearch/howto/oidc-authentication.rst
> +SSO authentication and authorization sequence
Do we actually need this, it is either something that the customer is familiar with or, if not, this in my opinion not that helpful for troubleshooting purposes.

2023-08-30 11:06 UTC, mteiste commented on docs/products/opensearch/howto/oidc-authentication.rst
> +
I would add section that would direct to Opensearch security documentation for assigning them to proper roles (unfortunately the official documentation is pretty bad regarding this). Not sure how much explaining we should do though.

2023-08-31 08:55 UTC, mteiste approved these changes

2023-08-31 08:55 UTC, merged