Kafka tiered storage concept content
aiven/devportal pull request #2142
Opened 2023-09-12 09:08 UTC by harshini-rangaswamy

# What changed, and why it matters

Aiven for Apache Kafka tiered storage concept content: 
 - Overview
 - How it works 
 - Guarantee
 - Limitations

2023-10-02 15:31 UTC, jeqo approved these changes
LGTM, thanks @harshini-rangaswamy!

2023-10-06 16:53 UTC, jeqo commented on docs/products/kafka/concepts/tiered-storage-how-it-works.rst
> +When consumers fetch records stored in remote storage, the broker downloads and caches these records locally. This allows for quicker access in subsequent retrieval operations.
Include comment about local disk cache:
```suggestion
When consumers fetch records stored in remote storage, the broker downloads and caches these records locally. This allows for quicker access in subsequent retrieval operations.
Aiven will use a small amount of disk (between 2GB and 16GB, based on the 5% of disk available on the broker) to store records fetched temporally.
```

2023-11-03 11:36 UTC, ivanyu requested changes
One small comment

2023-11-03 11:36 UTC, ivanyu commented on docs/products/kafka/concepts/tiered-storage-how-it-works.rst
> +Data is transferred to remote storage asynchronously and does not interfere with the producer activity. While the broker aims to move data as swiftly as possible, certain conditions, such as high-thr
```suggestion
Data is transferred to remote storage asynchronously and does not interfere with the producer activity. While the broker aims to move data as swiftly as possible, certain conditions, such as high ingestion rate or connectivity issues, may cause more data to be stored in the local storage than the specified local retention policy.
```

2023-11-03 12:18 UTC, merged