postgres: Adding docs for creating a read only user.
aiven/devportal pull request #2168
Opened 2023-10-03 19:11 UTC by richard-joerger-aiven

# What changed, and why it matters
Added a page on how to create read only users' on our platform. Helpful for deflecting support requests. Reached out to the SME's about some possible approaches for creating read only users on our platform. Useful in cases where a customer wants to limit a users' ability to access data.

2023-10-06 13:26 UTC, wojcik-dorota requested changes
Many thanks for adding this instructions :-)

2023-11-08 20:35 UTC, richard-joerger-aiven commented on docs/products/postgresql/howto/readonly-user.rst
> +1. Alter the default permissions for the role for the given schema: ``ALTER DEFAULT PRIVILEGES FOR ROLE <target role> IN SCHEMA <schema name> abbreviated_grant_or_revoke``
RE: abbreviated_grant_or_revoke, yes that is something the user would have to replace with their desired permissions. Shall I replace it with `<grant or revoke>`?

2023-11-08 20:40 UTC, richard-joerger-aiven commented on docs/products/postgresql/howto/readonly-user.rst
> +1. Create a new database which will be used as a template ``CREATE DATABASE ro_<name>_template...``
The standard information in this case would be the specific permissions that the CU would like to have be part of their template. Shall I say apply standard permissions & roles instead?

2023-11-09 06:24 UTC, wojcik-dorota commented on docs/products/postgresql/howto/readonly-user.rst
> +1. Create a new database which will be used as a template ``CREATE DATABASE ro_<name>_template...``
Thanks, that makes sense! how about
`2. For the new template database, set permissions and roles that you want as default ones in the template.`

2023-11-09 06:29 UTC, wojcik-dorota commented on docs/products/postgresql/howto/readonly-user.rst
> +1. Alter the default permissions for the role for the given schema: ``ALTER DEFAULT PRIVILEGES FOR ROLE <target role> IN SCHEMA <schema name> abbreviated_grant_or_revoke``
Let's use
`YOUR_GRANT_OR_REVOKE_PERMISSIONS`

2023-11-09 06:34 UTC, wojcik-dorota commented on docs/products/postgresql/howto/readonly-user.rst
> +1. Alter the default permissions for the role for the given schema: ``ALTER DEFAULT PRIVILEGES FOR ROLE <target role> IN SCHEMA <schema name> abbreviated_grant_or_revoke``
Also, usually we use all-caps (a word with all the letters in the upper case) for variables or placeholders (as YOUR_GRANT_OR_REVOKE_PERMISSIONS). I see you use it for whole queries. Is that possible for you to update the queries and remove all-caps words/expressions unless required by the SQL standard?

2023-11-14 13:42 UTC, wojcik-dorota requested changes

2023-11-14 13:42 UTC, wojcik-dorota commented on docs/products/postgresql/howto/list-dba-tasks.rst
> +    .. grid-item-card:: :doc:`Use the PostgreSQL® pg_repack extension </docs/productspostgresql/howto/use-pg-repack-extension>`
In `</docs/productspostgresql/howto/use-pg-repack-extension>`, the slash is missing after `products`.

2023-12-27 07:15 UTC, wojcik-dorota approved these changes
Thank you :-)

2023-12-27 07:24 UTC, merged