Fix PostgreSQL NodeJS code sample
aiven/devportal pull request #218
Opened 2021-09-23 09:41 UTC by jonatasbaldin

Hi there 💃

This PR makes the PostgreSQL NodeJS code sample article sample self-executable.

As you can see on the code sample, there's a bug from the ``pg`` library when using the `connectionString` parameter. Basically, the `?sslmode=require` string messes around with the `ssl` configuration, so I stripped it off.

Another workaround is to _not_ use the `connectionString`, but use all the parameters separated, like:
```js
const client = new Client({
  user: 'dbuser',
  host: 'database.server.com',
  database: 'mydb',
  password: 'secretpassword',
  port: 3211,
})
```

I still prefer the first one, when the user has less trouble copying/pasting connection details but has a bit more of code boilerplate.

What do you think?

2021-09-23 10:57 UTC, aiven-hh commented on code/products/postgresql/connect.js
> +        ca: fs.readFileSync(path.join(__dirname, '/ca.pem')),
The slash in not necessary before ca.pem.

2021-09-23 11:00 UTC, aiven-hh commented
Is php page still missing the step to download the cert or is that in another pr?

2021-09-24 13:59 UTC, lornajane requested changes
This change makes some assumptions about how the user is running the code, that I think makes it less portable. If it's an existing project, creating the directory isn't the right thing (and strictly speaking, is not a pre-requisite, so shouldn't be included).

We can't always assume filesystem access (for example if this is a lambda function usage, or the code is deployed to a cloud service like Heroku) - so to include the CA, perhaps we can create some separate content on how to handle the certificates in different environments, rather than hardcoding a filename.

2021-09-30 10:06 UTC, lornajane commented
Replaced by #265

2021-09-30 10:06 UTC, closed without merging