updated various broken links
aiven/devportal pull request #2194
Opened 2023-10-23 23:15 UTC by runwuf

updated various broken links

2023-10-24 08:04 UTC, staceysalamon-aiven requested changes
Update on the Terraform page looks good! Thanks!

2023-10-24 08:04 UTC, staceysalamon-aiven commented on docs/tools/terraform/get-started.rst
> +    For more details, refer to the :doc:`Project member roles page</docs/platform/reference/project-member-privileges>`.
```suggestion
    For more information, refer to the :doc:`project member roles page</docs/platform/reference/project-member-privileges>`.
```

2023-10-24 08:04 UTC, staceysalamon-aiven commented on docs/tools/terraform/get-started.rst
> +    For more details, refer to the :doc:`Project member roles page</docs/platform/reference/project-member-privileges>`.
Thanks for fixing this link!

2023-10-29 17:11 UTC, wojcik-dorota requested changes

2023-10-29 17:11 UTC, wojcik-dorota commented on docs/products/clickhouse/howto/connect-with-clickhouse-cli.rst
> +    There are other installation options available for ClickHouse clients for different operating systems. You can find them in `Install ClickHouse-client and ClickHouse-local <https://clickhouse.com
Please replace the linked docs' titles as follows:
- "Install ClickHouse-client and ClickHouse-local" => "clickhouse-local"
- "Available Installation Options" => "Install ClickHouse"

2023-10-29 17:11 UTC, wojcik-dorota commented on docs/products/clickhouse/howto/connect-with-go.rst
> +    * For instructions on how to configure connection settings, see `Connection settings <https://clickhouse.com/docs/en/integrations/go#connection-details>`_.
Please replace the linked doc' title as follows:

"Connection settings" => "Connection Details"

2023-10-31 13:45 UTC, wojcik-dorota commented on docs/products/clickhouse/howto/connect-with-clickhouse-cli.rst
> +    There are other installation options available for ClickHouse clients for different operating systems. You can find them in `clickhouse-local <https://clickhouse.com/docs/en/operations/utilities/
Two more fixes please for the doc titles:
ClickHouse local
and
Install ClickHouse

2023-11-01 06:39 UTC, wojcik-dorota approved these changes
Thank you! The ClickHouse part LGTM.

Plz acquire approval from @harshini-rangaswamy for the Kafka part before merging.

2023-11-02 09:16 UTC, harshini-rangaswamy commented on docs/products/kafka/kafka-mirrormaker/reference/known-issues.rst
> +The following are known issues that are expected to be resolved in version 3.3.0. See  :doc:`recommended tuning paramters</docs/products/kafka/kafka-mirrormaker/concepts/mirrormaker2-tuning>` to mini
```suggestion
The following are known issues that are expected to be resolved in version 3.3.0. See  :doc:`recommended tuning paramters</docs/products/kafka/kafka-mirrormaker/concepts/mirrormaker2-tuning>`  to mitigate the impact of these issues.
```

2023-11-02 09:27 UTC, harshini-rangaswamy approved these changes
@runwuf, a minor change to the text. The rest looks good. Thanks!

2023-11-03 05:58 UTC, harshini-rangaswamy approved these changes

2023-11-03 05:58 UTC, merged