Updated GCP VPC peering how-to
aiven/devportal pull request #2217
Opened 2023-11-03 00:40 UTC by runwuf

GCP Console has changed, updating the instruction to reflect with the latest UI.

2023-11-03 07:17 UTC, wojcik-dorota requested changes
Thanks so much for this update :-) A few editorial comment..

2023-11-03 07:17 UTC, wojcik-dorota commented on docs/platform/howto/vpc-peering-gcp.rst
> +3. Click the project name and make note of the **Project ID**.
Comma missing:
```
..., and make note of **Project ID**.
```

2023-11-03 07:17 UTC, wojcik-dorota commented on docs/platform/howto/vpc-peering-gcp.rst
> +9. Enter a name for the peering connection, under **Peered VPC network** select **In another project** and enter the **Aiven project ID** and **VPC network name** that you found in step 7 from Aiven
```
9. To create a peering connection, take the following steps:

    1. Enter a name for the peering connection.
    2. Under **Peered VPC network**, select **In another project**.
    3. Enter the Aiven project ID and the VPC network name identified in step 7 in Aiven Console.
```

2023-11-15 22:32 UTC, runwuf commented
sorry for the delay @wojcik-dorota it's ready to be re-reviewed again, thanks!

2023-11-16 09:42 UTC, wojcik-dorota requested changes

2023-11-16 09:42 UTC, wojcik-dorota commented on docs/platform/howto/vpc-peering-gcp.rst
> +    3. Enter the Aiven project ID and the VPC network name identified in step 7 in Aiven Console.
The indent here is too deep. Please you the 3-chars indent coz otherwise it renders incorrectly on the docs website.

2023-11-17 05:54 UTC, wojcik-dorota approved these changes
LGTM! Many thanks 🙏🏻

2023-11-17 05:54 UTC, merged