doc,kafka: add troubleshooting consumer disconnection
aiven/devportal pull request #2284
Opened 2023-11-23 18:58 UTC by jclarysse

What changed, and why it matters

Like for other services, adding troubleshooting section to Kafka doc and a first article dedicated to consumer disconnections. Aiven customer support receives quite a high number of related cases where customers have the impression that consumer re-balancing is a cluster pathology rather than a symptom that something is going wrong with their consumers. The benefit of this change is to make them more autonomous, and to allow us to become more efficient and consistent in our replies.

https://aiven.atlassian.net/browse/HELP-166

2023-12-08 12:13 UTC, pparmin requested changes
After fixing the minor errors reported by `vale` this is ready to merge.

2023-12-08 12:13 UTC, pparmin commented on docs/products/kafka/troubleshooting/troubleshoot-consumer-disconnections.rst
> +Troubleshoot Kafka consumer connections
replacing "Kafka" with "Apache Kafka®" should fix this error

2023-12-08 12:13 UTC, pparmin commented on docs/products/kafka/troubleshooting/troubleshoot-consumer-disconnections.rst
> +Kafka consumers sometimes experience disconnections from a cluster node. On one hand, isolated occurences are expected and well mitigated by the Kafka protocol, for example in case a partition leader
"occurences" --> "occurrences"

2023-12-08 12:13 UTC, pparmin commented on docs/products/kafka/troubleshooting/troubleshoot-consumer-disconnections.rst
> +As they are processing messages, consumer instances may break, fail to request more local resources or to complete their current task on time. In this case, they leave their group either explicitely
"explicitely" --> "explicitly"

2024-01-24 09:18 UTC, ArthurFlageul approved these changes

2024-01-24 09:20 UTC, merged