platform: improve terminology for service version life cycle
aiven/devportal pull request #2360
Opened 2023-12-13 16:43 UTC by wojcik-dorota

https://aiven.atlassian.net/browse/DOC-684

2023-12-13 17:03 UTC, ArthurFlageul requested changes

2023-12-13 17:03 UTC, ArthurFlageul commented on docs/platform/reference/eol-for-major-versions.rst
> +|             |               | supported by**     | supported from**   |
supported until?

2023-12-13 22:00 UTC, ArthurFlageul approved these changes
👍

2023-12-14 09:45 UTC, ken-tune approved these changes
This is definitely clearer. Thank-you.

2023-12-14 10:06 UTC, merged