Clarify Add Kafka producer and consumer Datadog metrics
aiven/devportal pull request #2385
Opened 2023-12-20 06:04 UTC by juha-aiven

First, remove the false claim that kafka.producer.* and kafka.consumer.* metrics are client side. Some broker-side metrics also have the prefix.

Change the topic to clearly state the page is about client-side metrics.

2023-12-20 07:30 UTC, harshini-rangaswamy requested changes
Thanks for updating this content,suggested some minor text changes.

2023-12-20 07:30 UTC, harshini-rangaswamy commented on docs/products/kafka/howto/add-missing-producer-consumer-metrics.rst
> +Additionally, metrics client-side metrics can be collected from the producer or consumer itself, and sent to Datadog. The dedicated `Datadog documentation <https://docs.datadoghq.com/integrations/faq
```suggestion
Additionally, you can collect client-side metrics directly from the producer or consumer and send them to Datadog. For guidance, refer to the *Missing producer and consumer metrics* section in the `Datadog documentation <https://docs.datadoghq.com/integrations/faq/troubleshooting-and-deep-dive-for-kafka>`_, which outlines the process for integrating missing metrics natively for Java-based producers and consumers. For clients using languages other than Java, incorporating these metrics can be achieved through `DogStatsD <https://docs.datadoghq.com/developers/dogstatsd/>`_.
```

2023-12-20 08:22 UTC, juha-aiven commented on docs/products/kafka/howto/add-missing-producer-consumer-metrics.rst
> +Additionally, metrics client-side metrics can be collected from the producer or consumer itself, and sent to Datadog. The dedicated `Datadog documentation <https://docs.datadoghq.com/integrations/faq
Thanks. I made this change.

2023-12-20 08:31 UTC, harshini-rangaswamy approved these changes
LGTM

2023-12-22 08:22 UTC, AnatolyPopov approved these changes
LGTM

2023-12-22 08:25 UTC, merged