Kafka datadog: clarify Kafka metrics vs Kafka consumer metrics
aiven/devportal pull request #2386
Opened 2023-12-20 06:36 UTC by juha-aiven

# What

Split the chapter of customising metrics into two - first for the main Kafka integration and the other for the  Consumer Integration.

Add an example how to use exclude_topics.

# Why

The issue was that documentation failed to mention that the four keys include_topics, exclude_topics, include_consumer_groups and exclude_consumer_groups only affect the consumer integration. And that kafka_custom_metrics applies to Kafka integration.

2023-12-20 09:21 UTC, harshini-rangaswamy commented on docs/products/kafka/howto/datadog-customised-metrics.rst
> +As example to sent the ``kafka.log.log_size`` and ``kafka.log.log_end_offset`` metrics execute the following code:
```suggestion
For example, to send the ``kafka.log.log_size`` and ``kafka.log.log_end_offset`` metrics, execute the folllowing code:
```

2023-12-20 09:22 UTC, harshini-rangaswamy commented on docs/products/kafka/howto/datadog-customised-metrics.rst
> +Customise Apache Kafka® Consumer Integration metrics sent to Datadog
Do you think we can shorten the heading a bit, say something like: 

Customize  Apache Kafka® consumer metrics for Datadog
-----------------------------------------------------------

2023-12-20 09:23 UTC, harshini-rangaswamy commented on docs/products/kafka/howto/datadog-customised-metrics.rst
> +.. Tip::
```suggestion
  .. Note::
```

2023-12-20 09:23 UTC, harshini-rangaswamy commented on docs/products/kafka/howto/datadog-customised-metrics.rst
> +.. Tip::
I think "Note" is better than a "Tip" here.

2023-12-20 09:23 UTC, harshini-rangaswamy commented on docs/products/kafka/howto/datadog-customised-metrics.rst
> +As example to include topics ``topic1`` and ``topic2`` and exclude topic ``topic3`` execute the following code:
```suggestion
For example, to include topics ``topic1`` and ``topic2``, and exclude ``topic3``, execute the following code:
```

2023-12-20 09:25 UTC, harshini-rangaswamy requested changes
Added some minor suggestions.

2023-12-20 09:52 UTC, juha-aiven commented
Could you @harshini-rangaswamy apply the changes directly in the branch? As long as they are this kind of formatting, spelling etc related changes, I'm 100% fine with those. The main thing that the PR does is to split the page in to the chapters and if that's fine for you, I'm sure you figure out a better layout and formatting than me. 🙇🏻

2023-12-21 08:19 UTC, harshini-rangaswamy approved these changes

2024-01-11 09:46 UTC, AnatolyPopov approved these changes

2024-01-11 09:47 UTC, merged