#341 Migrate Integration of logs into Apache Kafka topic
aiven/devportal pull request #344
Opened 2021-11-18 22:15 UTC by anelook

Migrated article https://help.aiven.io/en/articles/4888136-kafka-logs-integration

2021-11-22 18:07 UTC, lornajane commented on docs/products/kafka/howto/integrate-service-logs-into-kafka-topic.rst
> +Go to the overview page of your PostgeSQL service, scroll the list of actions till you see **Service integrations** and click on **Manage Integrations**. A new pop up window will be displayed showing
Typo PostgeSQL (it can't pick up things it thinks are an acronym - but we could add it to the suggestions list)

2021-11-23 13:00 UTC, ftisiot requested changes
Good work! Minor comments!

2021-11-23 13:00 UTC, ftisiot commented on docs/products/kafka/howto/integrate-service-logs-into-kafka-topic.rst
> +If you want to edit or remove the integration, use **Manage Integrations** in the source service. You'll see the created destination service in the list of **Enabled service integrations**, you can e
I would rephrase 
> You'll see the created destination service in the list of **Enabled service integrations**, you can edit or remove it from here.
to 
> The kafka-logs integration is listed in the **Enabled service integrations** section, from where you can edit or remove it.

2021-11-23 16:27 UTC, anelook commented on .github/styles/Aiven/common_replacements.yml
> +  PostgreSQL: PostgreSQL
Oh no... I even tested that it pointed me to the error!

2021-11-23 16:41 UTC, anelook commented
Thank you! Agree with the suggestions, added them.

2021-11-24 09:12 UTC, ftisiot requested changes
I would move the main Setup paragraph to a list of points to follow, in line with the other pages we have

2021-11-24 09:12 UTC, ftisiot commented on docs/products/kafka/howto/integrate-service-logs-into-kafka-topic.rst
> +Navigate to the Aiven console overview page of the source PostgreSQL service, scroll the list of actions till you see **Service integrations** and click on **Manage Integrations**. A new pop up windo
Should this be a list of points to follow? Would make it easier to read and follow

2021-11-24 11:04 UTC, lornajane commented on docs/products/kafka/howto/integrate-service-logs-into-kafka-topic.rst
> +Setup Apache Kafka to receive the logs
Set up is two words when you are setting something up. If you are talking about your shiny new setup (a noun) it's one word.

2021-11-24 12:36 UTC, ftisiot requested changes
One small comment, almost there!

2021-11-24 12:36 UTC, ftisiot commented on docs/products/kafka/howto/integrate-service-logs-into-kafka-topic.rst
> +1. Go to the destination service overview page.
Should we state that these steps can be done only if your target Kafka is within Aiven? (and if it's an external kafka just check that the topic receives data)

2021-11-25 08:32 UTC, ftisiot approved these changes
Good work!

2021-11-25 08:32 UTC, merged