Migrate upgrading-elasticsearch-clients-to-opensearch
aiven/devportal pull request #360
Opened 2021-11-23 16:11 UTC by anelook

There was recently added a help article on migration of elasticsearch clients to opensearch.

2021-11-24 11:57 UTC, lornajane requested changes
I find this article a little bit jumbled - I know it's a migration but I think we can get it a more more like a "How To" to fit the devportal content format we usually use with numbered steps:
 - Newer Elasticsearch clients don't work with OpenSearch, so you will need to switch.
 - First, pin your ElasticSearch libraries at <version>
 - Switch from that to the OpenSearch clients (using all the excellent resources we referred to)
 - Migrate from ElasticSearch to OpenSearch with your Aiven service (you can do this before or after switching the clients, and we have an excellent article for you.

Do you think we can refactor?

2021-11-24 11:57 UTC, lornajane commented on docs/products/opensearch/howto/upgrade-clients-to-opensearch.rst
> +Java and Spring Boot
We might need to add Spring and Boot as words to the allow list

2021-11-25 10:11 UTC, anelook commented
Refactored, let me know if this is closer to what you meant.

2021-11-26 09:51 UTC, lornajane approved these changes
Looking good! Thanks :)

2021-11-26 09:51 UTC, merged