Adding disclaimer in the footer
aiven/devportal pull request #549
Opened 2022-02-07 18:09 UTC by dewan-ahmed

# What changed, and why it matters

The existing DevPortal pages don't have disclaimers. Rather than adding the disclaimer individually on each page, this PR adds the disclaimer in the template that will be reflected to all DevPortal pages as a footer.

Fix https://github.com/aiven/devportal/issues/485

2022-02-09 13:24 UTC, lornajane commented
Please add a more meaningful description to your pull request. This is required for all the changes on the repo (and you will write this message yourself as a reviewer!)

2022-02-09 13:27 UTC, TibsAtWork commented
@dewan-ahmed  There is a new version of the attribution text as of noon yesterday, which I think we should adopt, and then I'll happily approve this and we can get it out. We'll then need to monitor the situation, as I expect that there may be more (minor) changes in the future.

2022-02-09 13:28 UTC, lornajane requested changes
The required text has changed to:

```
Apache, Apache Kafka, Kafka, Apache Flink, Flink, Apache Cassandra, and Cassandra are either registered trademarks or trademarks of the Apache Software Foundation in the United States and/or other countries. M3, M3 Aggregator, M3 Coordinator, OpenSearch, PostgreSQL, MySQL, InfluxDB, Grafana, Terraform, and Kubernetes are trademarks and property of their respective owners. *Redis is a trademark of Redis Ltd. Any rights therein are reserved to Redis Ltd. Any use by Aiven is for referential purposes only and does not indicate any sponsorship, endorsement or affiliation between Redis and Aiven. All product and service names used in this website are for identification purposes only and do not imply endorsement. 
```

Could you please use the CSS themes for styling instead of inline style tags? This will get more difficult to maintain over time if we mix structure and presentation styles in this way (also there are two stylesheets: one for dark mode as well as the main one)

2022-02-11 16:30 UTC, dewan-ahmed commented
Hi @lornajane would you like me to review+LGTM the change you made or wait till we have the associated CSS change as well?

2022-02-11 17:27 UTC, lornajane commented
The CSS change isn't trivial so let's follow up with that - we do need to update the PR to take in the new wording though before we can merge.

2022-02-11 19:23 UTC, dewan-ahmed commented
Hi @lornajane, by "we do need to update the PR", do you mean updating the PR description? I edited the PR description to explain what this PR is about.

2022-02-14 20:27 UTC, lornajane commented
I mean, as per this comment in the thread https://github.com/aiven/devportal/pull/549#pullrequestreview-877457792 , we need to update the change in this branch to reflect the new wording for the footer. Does this make sense? I can also pick this up quickly if needed.

2022-02-15 00:26 UTC, dewan-ahmed commented
@lornajane thanks. pushed a commit with the updated wording. 

 ```
 fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
  WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.10/main: temporary error (try again later)
  fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
  WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.10/community: temporary error (try again later)
  ERROR: unable to select packages:
    nodejs (no such package):
      required by: world[nodejs]
    nodejs-npm (no such package):
      required by: world[nodejs-npm]
  The command '/bin/sh -c apk add --no-cache --update nodejs nodejs-npm' returned a non-zero code: 2
  Warning: Docker build failed with exit code 2, back off 7.588 seconds before retry.


```
It seems to me that Linting / prose is failing due to some network issues. Please let me know if that's not the case. Is there a way to retest i.e. have the CI rerun the specific tests without adding an empty commit?

2022-02-15 09:09 UTC, lornajane commented
There is! If you click on "Details" next to the failed job, you should see a "Re-run all jobs" button someone near the top right hand side. I have clicked it now to see if things are working again yet this morning in my timezone

2022-02-15 14:44 UTC, dewan-ahmed commented
Thanks @lornajane . I see the tests have now passed.

2022-02-21 18:58 UTC, lornajane approved these changes

2022-02-21 18:59 UTC, merged