Add new document to talk about extra sphinx tips
aiven/devportal pull request #714
Opened 2022-04-07 09:23 UTC by TibsAtWork

Provide a place for sphinx/reStructuredText information that doesn't belong in README or CONTRIBUTING

Fix: https://github.com/aiven/devportal/issues/712

2022-04-10 15:19 UTC, lornajane commented
How about sharing the documentation about our documentation as part of our documentation? I know you like documentation!

(I'd also like to discuss/review some of these new tips) I think using the existing platform could make content more findable rather than in the buckets of randomness as it is right now, README and CONTRIBUTING are already fairly epic, we're adding these tips plus additional contribution approaches .... let's use something bookmarkable/linkable/navigable and nice to look at

2022-04-19 08:34 UTC, ftisiot commented
@TibsAtWork are you going to work on Lorna's comment?

2022-04-19 08:52 UTC, TibsAtWork commented
I'm happy if you want to take it on, @ftisiot - I don't think I'd get round to it in the next couple of days.

2022-05-04 13:13 UTC, ftisiot commented
Following @lornajane's comment, I put the Tips&tricks in the same format as our devportal under a "Documentation" section.
Could you please review and comment, I feel this is far from perfect

2022-05-04 13:59 UTC, laysauchoa commented
I thin this is also already good. However, we discussed the redirection today and I wonder if we can make a note not encouraging contributors to make redirection only if really needed it. I am not sure what would be the criteria here.

2022-05-25 18:56 UTC, lornajane requested changes
This redirects thing makes me really nervous, let's remove it from here and try to solve it a different way.

2022-05-25 18:56 UTC, lornajane commented on docs/documentation/tips-tricks/page-redirects.rst
> +Handle page redirects
Could we please remove this page? I'm opening #882 to take a less hacky approach to this problem by maintaining a list of redirects in configuration in the project.

2022-05-25 18:56 UTC, lornajane commented on docs/documentation/tips-tricks/anonymus-links.rst
> +Create anonymous links
File name is mispelled

2022-05-25 18:56 UTC, lornajane commented on docs/documentation/tips-tricks/page-redirects.rst
> +The ``:orphan:`` section tells Sphinx not to include this page in any contents list, which means that it does not issue a warning that ``database-forking.rst`` isn't included in the ``_toc.yaml`` fil
This orphan thing should be a tip by itself, we may want to have pages that aren't in the nav

2022-06-01 19:07 UTC, lornajane approved these changes

2022-06-01 19:07 UTC, merged