Add howto guide for m3db as prometheus storage
aiven/devportal pull request #722
Opened 2022-04-19 07:32 UTC by lornajane

# What changed, and why it matters

One big use case for M3 is using it as backend storage for Prometheus, so here's an article on configuring prometheus to do exactly that.

2022-04-20 12:32 UTC, anelook commented
@lornajane, I am trying to follow the steps, and I feel that comparing to our other articles there is a gap in information. This article for those users who already fluent at Prometheus, but for those who interested in expanding the back end storage, but who doesn't know Prometheus, a couple more  more pointers on how to start with Prometheus would be useful. 

However, I'm fine if this is intentionally kept so dry. I see that @dewan-ahmed is assigned as a reviewer. @dewan-ahmed, if you're familiar with prometheus, I'll leave this review for you. Otherwise I can dive in and figure out the setup.

2022-04-20 18:51 UTC, dewan-ahmed commented
@anelook I think that this article assumes that the reader is already familiar with Prometheus and looking for "How to do X with Prometheus?" 

I don't have advanced level knowledge but I have used Prometheus. I'm going to add a few review comments but please feel free to mention anything in addition to that.

2022-05-04 10:44 UTC, lornajane commented
Could you take another look please? I've added a link to a simple getting started guide so that people can also try this standalone; it includes a nice example of prometheus scraping itself which is a nice standalone starter example. Then how to configure with our M3DB as remote storage, and a clearer call to action that the best way to observe that the data is stored in M3 is to look in M3. My preferred way to do that is with Grafana and we have a guide on doing that already!

2022-05-06 19:36 UTC, dewan-ahmed commented
@lornajane I really like this - simple and just enough for the reader to follow the HowTo. Just nits over a style issue and a spelling one (UK vs. American). I already ran the steps last time 👍🏽

2022-05-07 11:20 UTC, lornajane commented
Dewan, I see your comment, but nothing else. No approved or request changes result, no indication of a style or spelling problem when I view the diff. Can you re-review please? (or make small changes and merge, is also fine)

2022-05-07 11:32 UTC, dewan-ahmed requested changes
Some grammatical and styling nits.

2022-05-13 16:26 UTC, lornajane commented
As a reviewer, feel free to make minor changes like these yourself before merging. I'll update it when I can, but I'd recommend not waiting for the author unless their expertise is needed, or the changes are extensive.

2022-05-16 17:58 UTC, dewan-ahmed approved these changes
LGTM

2022-05-16 17:58 UTC, merged