mysql: Fix small formatting
aiven/devportal pull request #729
Opened 2022-04-20 06:39 UTC by laysauchoa

So it can be easily maintained in the future

# What changed, and why it matters

2022-04-20 08:18 UTC, kevinbowman-aiven requested changes
Just a tiny typo fix, everything else looks good to me.

2022-04-20 08:18 UTC, kevinbowman-aiven commented on docs/products/mysql/howto/migrate-from-external-mysql.rst
> +* You have an user account on the source server with sufficient privileges to create a user for the replication process.
Should be "a", as in "You have a user account"

2022-04-21 15:41 UTC, laysauchoa commented
thanks @kevinbowman-aiven I've fixed now!

2022-04-21 15:42 UTC, kevinbowman-aiven approved these changes
Looks good to me!

2022-04-22 09:08 UTC, merged