Migrated MySQL Debezium connector
aiven/devportal pull request #833
Opened 2022-05-16 07:43 UTC by ftisiot

# What changed, and why it matters

Migrated MySQL debezium connector https://help.aiven.io/en/articles/3019477-setting-up-debezium-with-aiven-for-mysql, 

Fixes #791

2022-05-20 08:41 UTC, anelook reviewed
Just a couple of minor comments.

2022-05-20 08:41 UTC, anelook commented on docs/products/kafka/kafka-connect/howto/debezium-source-connector-mysql.rst
> +        "plugin.name": "PLUGIN_NAME",
"plugin.name": "PLUGIN_NAME",
        "slot.name": "MYSQL_SLOT_NAME",
        "publication.name": "MYSQL_PUBLICATION_NAME", - are they needed?

2022-05-20 08:53 UTC, ftisiot commented on docs/products/kafka/kafka-connect/howto/debezium-source-connector-mysql.rst
> +Schema versioning
I believe it's a compulsory piece and is different from others (e.g. postgresql) I would keep it here

2022-05-20 08:56 UTC, ftisiot commented on docs/products/kafka/kafka-connect/howto/debezium-source-connector-mysql.rst
> +    .. Warning::
Should be fixed now

2022-05-20 08:56 UTC, ftisiot commented on docs/products/kafka/kafka-connect/howto/debezium-source-connector-mysql.rst
> +        "plugin.name": "PLUGIN_NAME",
removed

2022-05-20 15:53 UTC, anelook requested changes
Left couple of minor points related to warning message and layout.
Thanks a lot for helping to setup connection and run my example. All worked.

2022-05-20 15:53 UTC, anelook commented on docs/products/kafka/kafka-connect/howto/debezium-source-connector-mysql.rst
> +Setup a MySQL Debezium source connector with Aiven Console
One of these words is probably not in our accepted list when first letter is capital, could you double check, so that we remove the warning?

2022-05-20 15:53 UTC, anelook commented on docs/products/kafka/kafka-connect/howto/debezium-source-connector-mysql.rst
> +   .. note::
There is different indentation between this note and tip below, even though for me they should be on the same level. Could you double check if this is intentional?

2022-05-24 11:35 UTC, anelook requested changes
Thanks for adding more changes. We have just one warning left - "[warning] Aiven.capitalization_headings
'Setup a MySQL Debezium source connector with Aiven Console' should be in sentence case" Could you check it?

2022-05-24 11:39 UTC, anelook approved these changes
Ignore my last comment - the warning I saw as part of commit, not the final PR version

2022-05-24 11:47 UTC, merged