Update BYOA docs with diagrams and clean up organization
aiven/devportal pull request #853
Opened 2022-05-17 18:33 UTC by ak-aiven

2022-05-17 20:36 UTC, lornajane reviewed
This definitely doesn't count as a review, just a few tips from my first glance! We have some lint checking built in so have a look at the comments from the bot as well as me. We're using mermaid for diagrams (yours are lovely but we won't be able to maintain or update them), do you think you could convert? Also if you do include images, these need alt tags (but the syntax check doesn't pick that up, it's on our list)

2022-05-18 10:07 UTC, ak-aiven commented
Thanks @lornajane. I changed the casing for the sub headings so the linter is a little happier now. I have already invested quite a bit of time in those diagrams and I am not sure I have the bandwidth to convert at this time. Those diagrams are taken from Lucidchart which is where the security team maintains these architectural references.

2022-05-19 13:33 UTC, ak-aiven commented
@encima do you want to convert these? :)

2022-05-20 10:15 UTC, lornajane commented
I recommend we review this as-is, replacing the diagrams at a later date if at all possible.

2022-05-23 15:03 UTC, dbeech requested changes
Left some comments. One general point of feedback is that the language could be simplified in several places, for example:

> When leveraging BYOA you will negate Aiven’s feature of paying for all network traffic out of the service.

vs

> Unlike Aiven's standard all-inclusive pricing, with BYOA you will be responsible for all cloud infrastructure and network traffic charges. 

I think the final "Testing, POC, and deployments" section needs work, but because there was no change there in this PR I could not comment in-line. 
- We say to allocate sufficient time but give no indication about how long that should be. hours, days, weeks... months??
- Despite the heading, we can't support BYOA during any kind of POC so maybe we should be clearer about that. 

There's an argument to say this last section shouldn't be in the docs at all. The guidance is too vague to be useful.

2022-05-23 15:36 UTC, ak-aiven commented on docs/platform/concepts/byoa.rst
> +in your own account we can do this as well. Aiven will need object storage and permissions
The only caveat that I know of is that they are still encrypted using our keys. So although the backups will be in their account they won't be able to utilize them. I originally had some comment about BYOK on our roadmap but was told to take it out.

2022-05-23 15:38 UTC, ak-aiven commented
I 100% agree about the last section and have completely removed it.

2022-05-25 19:28 UTC, merged