4th Terraform Recipe - Kafka and Mirrormaker2
aiven/devportal pull request #886
Opened 2022-05-26 23:23 UTC by dewan-ahmed

# What changed, and why it matters

Resolves https://github.com/aiven/devportal/issues/885

## Feedback requested:

- Please run the Terraform code and ensure that it works (I did multiple times and works from my end)
- I haven't used MirrorMaker before so please check if the descriptions of the flow makes sense
- I used *i1*, *i2*, *f1* naming which is not descriptive. Please let me know if I can improve the PR with a more descriptive naming 
- Please check if the Mermaid diagram makes sense
- Is the blog under the reference section appropriate to mention?
- Anything else that you find would improve this recipe

2022-05-27 03:49 UTC, dewan-ahmed commented
From a quick glance, my assumption is that the following broken link is causing the fail:

```
(docs/products/opensearch/howto/sample-dataset: line  157) broken    https://opensearch.org/docs/latest/opensearch/rest-api/index-apis/create-index/#mappings - Anchor 'mappings' not found
(docs/products/opensearch/howto/sample-dataset: line  240) broken    https://opensearch.org/docs/latest/opensearch/rest-api/index-apis/create-index/#dynamic-mapping-types - Anchor 'dynamic-mapping-types' not found
```

I'll check it in detail during the week of June6th.

2022-06-06 16:38 UTC, lornajane requested changes
Sharing this initial review for now - as discussed, the terraform recipe didn't set up the replication flow I expected, so that also needs checking.

2022-06-06 18:21 UTC, dewan-ahmed commented on docs/tools/terraform/reference/cookbook/kafka-mirrormaker-recipe.rst
> +      ip_filter = [
Thanks for the suggestion. I'm looking for more info on this config option and will include a few lines for the reader.

2022-06-06 18:55 UTC, dewan-ahmed commented on docs/tools/terraform/reference/cookbook/kafka-mirrormaker-recipe.rst
> +      ip_filter = [
@lornajane I'm waiting to gather more info on this specific config option. Once I have this info, I'll add it to the document and mark this comment as 'Resolved'.

2022-06-10 08:32 UTC, ftisiot requested changes
Tried it, but it fails with the following when calling `terraform plan`

```
╷
│ Error: Reference to undeclared resource
│
│   on services.tf line 2, in resource "aiven_kafka_mirrormaker" "mm":
│    2:   project      = data.aiven_project.kafka-mm-project1.project
│
│ A data resource "aiven_project" "kafka-mm-project1" has not been declared in the root module.
╵
╷
│ Error: Reference to undeclared resource
│
│   on services.tf line 61, in resource "aiven_kafka" "source":
│   61:  project                 = data.aiven_project.kafka-mm-project1.project
│
│ A data resource "aiven_project" "kafka-mm-project1" has not been declared in the root module.
╵
╷
│ Error: Reference to undeclared resource
│
│   on services.tf line 86, in resource "aiven_kafka" "target":
│   86:  project                 = data.aiven_project.kafka-mm-project1.project
│
│ A data resource "aiven_project" "kafka-mm-project1" has not been declared in the root module.
```

2022-06-10 13:00 UTC, dewan-ahmed commented
The recipes don't include the common files that are required for execution (for example, provider.tf, variables.tf, etc). But made a small change for the project name for consistency and added the following note:

.. Tip::

    Be sure to check out the :doc:`getting started guide <../../get-started>` to learn about the common files required to execute the following recipe. For example, you'll need to declare the variables for ``project_name`` and ``api_token``.

Please let me know if this helps you as a reader and I'll add this note to the other recipes as well.

2022-06-16 11:54 UTC, ftisiot commented
Hi Dewan, I changed the recipe to be a bit more readable and added a section at the end about what to expect and how to understand if it works. Let me know what you think of it

2022-06-16 15:29 UTC, mhoffm-aiven commented
I'm very much for making the manifests self-contained and including everything that it needs to run stand alone.

2022-06-16 18:54 UTC, dewan-ahmed commented
> I'm very much for making the manifests self-contained and including everything that it needs to run stand alone.

Hi @ftisiot @mhoffm-aiven I'll be making the change next quarter via https://github.com/aiven/devportal/issues/959

2022-06-16 19:30 UTC, dewan-ahmed commented
Hi @ftisiot I appreciate the changes/additions to this recipe. I reviewed them ✅

2022-06-17 07:17 UTC, ftisiot approved these changes
LGTM

2022-06-17 07:23 UTC, merged