Fixed formatting for embedded Terraform code within rst
aiven/devportal pull request #957
Opened 2022-06-15 18:53 UTC by dewan-ahmed

# What changed, and why it matters

Changes made thanks to @mhoffm-aiven and [his work](https://github.com/MichaHoffmann/terrafmt/tree/mhoffm-add-restructured-text-support).

2022-06-15 18:58 UTC, dewan-ahmed commented
I see that the formatting changes have caused the Terraform syntax highlighting to disappear 🤔 

I'll dig into this tomorrow.

2022-06-17 07:51 UTC, mhoffm-aiven commented on docs/tools/terraform/reference/cookbook/kafka-flink-integration-recipe.rst
> +    schema_sql     = <<EOF
please try "<<-EOF"; pygments has a bug parsing heredoc comments: https://github.com/pygments/pygments/issues/2162

2022-06-17 07:51 UTC, mhoffm-aiven commented on docs/tools/terraform/reference/cookbook/kafka-flink-integration-recipe.rst
>      schema_sql     = <<EOF
same here

2022-06-17 07:51 UTC, mhoffm-aiven commented on docs/tools/terraform/reference/cookbook/kafka-flink-integration-recipe.rst
>      statement = <<EOF
same here

2022-06-17 07:52 UTC, mhoffm-aiven commented on docs/tools/terraform/reference/cookbook/kafka-flink-integration-recipe.rst
> +.. code:: bash
lets try to make terraform work by working around pygments

2022-06-17 07:52 UTC, mhoffm-aiven requested changes
see comments

2022-06-17 08:03 UTC, mhoffm-aiven commented on docs/tools/terraform/reference/cookbook/kafka-flink-integration-recipe.rst
> +    schema_sql     = <<EOF
stripping the leading whitespace from the closing EOF is the proper way towrite it, technically pygments is spec conform there!

2022-06-17 14:45 UTC, dewan-ahmed commented
@mhoffm-aiven I tested producing messages to the source Kafka topic and the expected filtered messages show up in the sink topic. This validates that the formatted terraform code from the doc still works.

2022-06-17 14:53 UTC, dewan-ahmed commented
I see that the _toc.yml is missing two recipes that have been merged since. I'll wait before merging as I add one more commit to fix the _toc.yml

2022-06-17 15:05 UTC, merged